name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build AAR
        run: ./gradlew assembleRelease 

      - name: Build JVM JAR
        run: ./gradlew :yourJvmModule:jar

      - name: Upload AAR
        uses: actions/upload-artifact@v3
        with:
          name: aar-artifacts
          path: PixelPaletteAndroid/build/outputs/aar/*.aar

      - name: Upload JVM JAR
        uses: actions/upload-artifact@v3
        with:
          name: jvm-artifacts
          path: PixelPaletteJvm/build/libs/*.jar

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Automated release of AAR and JAR artifacts.
          files: |
            PixelPaletteAndroid/build/outputs/aar/*.aar  # Adjust for your module path
            PixelPaletteJvm/build/libs/*.jar  # Adjust for your JVM module path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
